# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(722, 544)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.overallHorizontalLayout = QtWidgets.QHBoxLayout()
        self.overallHorizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.overallHorizontalLayout.setObjectName("overallHorizontalLayout")
        self.calculationsVerticalLayout = QtWidgets.QVBoxLayout()
        self.calculationsVerticalLayout.setContentsMargins(5, 5, 5, 5)
        self.calculationsVerticalLayout.setObjectName("calculationsVerticalLayout")
        self.calculationsLineEdit = QtWidgets.QLineEdit(Dialog)
        self.calculationsLineEdit.setObjectName("calculationsLineEdit")
        self.calculationsVerticalLayout.addWidget(self.calculationsLineEdit)
        self.buttonsGridLayout = QtWidgets.QGridLayout()
        self.buttonsGridLayout.setObjectName("buttonsGridLayout")
        self.addPushButton = QtWidgets.QPushButton(Dialog)
        self.addPushButton.setObjectName("addPushButton")
        self.buttonsGridLayout.addWidget(self.addPushButton, 3, 4, 1, 1)
        self.sixPushButton = QtWidgets.QPushButton(Dialog)
        self.sixPushButton.setObjectName("sixPushButton")
        self.buttonsGridLayout.addWidget(self.sixPushButton, 2, 3, 1, 1)
        self.ninePushButton = QtWidgets.QPushButton(Dialog)
        self.ninePushButton.setObjectName("ninePushButton")
        self.buttonsGridLayout.addWidget(self.ninePushButton, 1, 3, 1, 1)
        self.subtractPushButton = QtWidgets.QPushButton(Dialog)
        self.subtractPushButton.setObjectName("subtractPushButton")
        self.buttonsGridLayout.addWidget(self.subtractPushButton, 2, 4, 1, 1)
        self.cubePushButton = QtWidgets.QPushButton(Dialog)
        self.cubePushButton.setObjectName("cubePushButton")
        self.buttonsGridLayout.addWidget(self.cubePushButton, 3, 0, 1, 1)
        self.onePushButton = QtWidgets.QPushButton(Dialog)
        self.onePushButton.setObjectName("onePushButton")
        self.buttonsGridLayout.addWidget(self.onePushButton, 3, 1, 1, 1)
        self.fivePushButton = QtWidgets.QPushButton(Dialog)
        self.fivePushButton.setObjectName("fivePushButton")
        self.buttonsGridLayout.addWidget(self.fivePushButton, 2, 2, 1, 1)
        self.threePushButton = QtWidgets.QPushButton(Dialog)
        self.threePushButton.setObjectName("threePushButton")
        self.buttonsGridLayout.addWidget(self.threePushButton, 3, 3, 1, 1)
        self.eightPushButton = QtWidgets.QPushButton(Dialog)
        self.eightPushButton.setObjectName("eightPushButton")
        self.buttonsGridLayout.addWidget(self.eightPushButton, 1, 2, 1, 1)
        self.undoPushButton = QtWidgets.QPushButton(Dialog)
        self.undoPushButton.setObjectName("undoPushButton")
        self.buttonsGridLayout.addWidget(self.undoPushButton, 0, 3, 1, 1)
        self.multiplyPushButton = QtWidgets.QPushButton(Dialog)
        self.multiplyPushButton.setObjectName("multiplyPushButton")
        self.buttonsGridLayout.addWidget(self.multiplyPushButton, 1, 4, 1, 1)
        self.dividePushButton = QtWidgets.QPushButton(Dialog)
        self.dividePushButton.setObjectName("dividePushButton")
        self.buttonsGridLayout.addWidget(self.dividePushButton, 0, 4, 1, 1)
        self.twoPushButton = QtWidgets.QPushButton(Dialog)
        self.twoPushButton.setObjectName("twoPushButton")
        self.buttonsGridLayout.addWidget(self.twoPushButton, 3, 2, 1, 1)
        self.modulusPushButton = QtWidgets.QPushButton(Dialog)
        self.modulusPushButton.setObjectName("modulusPushButton")
        self.buttonsGridLayout.addWidget(self.modulusPushButton, 0, 0, 1, 1)
        self.squarePushButton = QtWidgets.QPushButton(Dialog)
        self.squarePushButton.setObjectName("squarePushButton")
        self.buttonsGridLayout.addWidget(self.squarePushButton, 2, 0, 1, 1)
        self.clearPushButton = QtWidgets.QPushButton(Dialog)
        self.clearPushButton.setObjectName("clearPushButton")
        self.buttonsGridLayout.addWidget(self.clearPushButton, 0, 1, 1, 2)
        self.sevenPushButton = QtWidgets.QPushButton(Dialog)
        self.sevenPushButton.setObjectName("sevenPushButton")
        self.buttonsGridLayout.addWidget(self.sevenPushButton, 1, 1, 1, 1)
        self.fourPushButton = QtWidgets.QPushButton(Dialog)
        self.fourPushButton.setObjectName("fourPushButton")
        self.buttonsGridLayout.addWidget(self.fourPushButton, 2, 1, 1, 1)
        self.sqrtPushButton = QtWidgets.QPushButton(Dialog)
        self.sqrtPushButton.setObjectName("sqrtPushButton")
        self.buttonsGridLayout.addWidget(self.sqrtPushButton, 1, 0, 1, 1)
        self.zeroPushButton = QtWidgets.QPushButton(Dialog)
        self.zeroPushButton.setObjectName("zeroPushButton")
        self.buttonsGridLayout.addWidget(self.zeroPushButton, 4, 2, 1, 1)
        self.negatePushButton = QtWidgets.QPushButton(Dialog)
        self.negatePushButton.setObjectName("negatePushButton")
        self.buttonsGridLayout.addWidget(self.negatePushButton, 4, 1, 1, 1)
        self.decimalPushButton = QtWidgets.QPushButton(Dialog)
        self.decimalPushButton.setObjectName("decimalPushButton")
        self.buttonsGridLayout.addWidget(self.decimalPushButton, 4, 3, 1, 1)
        self.enterPushButton = QtWidgets.QPushButton(Dialog)
        self.enterPushButton.setObjectName("enterPushButton")
        self.buttonsGridLayout.addWidget(self.enterPushButton, 4, 4, 1, 1)
        self.inversePushButton = QtWidgets.QPushButton(Dialog)
        self.inversePushButton.setObjectName("inversePushButton")
        self.buttonsGridLayout.addWidget(self.inversePushButton, 4, 0, 1, 1)
        self.calculationsVerticalLayout.addLayout(self.buttonsGridLayout)
        self.overallHorizontalLayout.addLayout(self.calculationsVerticalLayout)
        self.historyVerticalLayout = QtWidgets.QVBoxLayout()
        self.historyVerticalLayout.setContentsMargins(5, 5, 5, 5)
        self.historyVerticalLayout.setObjectName("historyVerticalLayout")
        self.historyLabel = QtWidgets.QLabel(Dialog)
        self.historyLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.historyLabel.setObjectName("historyLabel")
        self.historyVerticalLayout.addWidget(self.historyLabel)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setObjectName("listWidget")
        self.historyVerticalLayout.addWidget(self.listWidget)
        self.overallHorizontalLayout.addLayout(self.historyVerticalLayout)
        self.gridLayout.addLayout(self.overallHorizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addPushButton.setText(_translate("Dialog", "+"))
        self.sixPushButton.setText(_translate("Dialog", "6"))
        self.ninePushButton.setText(_translate("Dialog", "9"))
        self.subtractPushButton.setText(_translate("Dialog", "-"))
        self.cubePushButton.setText(_translate("Dialog", "cube"))
        self.onePushButton.setText(_translate("Dialog", "1"))
        self.fivePushButton.setText(_translate("Dialog", "5"))
        self.threePushButton.setText(_translate("Dialog", "3"))
        self.eightPushButton.setText(_translate("Dialog", "8"))
        self.undoPushButton.setText(_translate("Dialog", "UNDO"))
        self.multiplyPushButton.setText(_translate("Dialog", "X"))
        self.dividePushButton.setText(_translate("Dialog", "/"))
        self.twoPushButton.setText(_translate("Dialog", "2"))
        self.modulusPushButton.setText(_translate("Dialog", "%"))
        self.squarePushButton.setText(_translate("Dialog", "square"))
        self.clearPushButton.setText(_translate("Dialog", "CLEAR"))
        self.sevenPushButton.setText(_translate("Dialog", "7"))
        self.fourPushButton.setText(_translate("Dialog", "4"))
        self.sqrtPushButton.setText(_translate("Dialog", "squareRoot"))
        self.zeroPushButton.setText(_translate("Dialog", "0"))
        self.negatePushButton.setText(_translate("Dialog", "(-)"))
        self.decimalPushButton.setText(_translate("Dialog", "."))
        self.enterPushButton.setText(_translate("Dialog", "ENTER"))
        self.inversePushButton.setText(_translate("Dialog", "1/x"))
        self.historyLabel.setText(_translate("Dialog", "History:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

