# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(722, 544)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.overallHorizontalLayout = QtWidgets.QHBoxLayout()
        self.overallHorizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.overallHorizontalLayout.setObjectName("overallHorizontalLayout")
        self.calculationsVerticalLayout = QtWidgets.QVBoxLayout()
        self.calculationsVerticalLayout.setContentsMargins(5, 5, 5, 5)
        self.calculationsVerticalLayout.setObjectName("calculationsVerticalLayout")
        self.calculationsLineEdit = QtWidgets.QLineEdit(Dialog)
        self.calculationsLineEdit.setObjectName("calculationsLineEdit")
        self.calculationsLineEdit.setTextMargins(10, 10, 10, 10)
        lineEditFont = self.calculationsLineEdit.font()
        lineEditFont.setPointSize(35)
        self.calculationsLineEdit.setFont(lineEditFont)
        self.calculationsLineEdit.setReadOnly(True)
        self.calculationsVerticalLayout.addWidget(self.calculationsLineEdit)
        self.buttonsGridLayout = QtWidgets.QGridLayout()
        self.buttonsGridLayout.setObjectName("buttonsGridLayout")
        self.addPushButton = QtWidgets.QPushButton(Dialog)
        self.addPushButton.setObjectName("addPushButton")
        addButtonFont = self.addPushButton.font()
        addButtonFont.setPointSize(16)
        self.addPushButton.setFont(addButtonFont)
        self.addPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.addPushButton, 3, 4, 1, 1)
        self.sixPushButton = QtWidgets.QPushButton(Dialog)
        self.sixPushButton.setObjectName("sixPushButton")
        sixButtonFont = self.sixPushButton.font()
        sixButtonFont.setPointSize(16)
        self.sixPushButton.setFont(sixButtonFont)
        self.sixPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.sixPushButton, 2, 3, 1, 1)
        self.ninePushButton = QtWidgets.QPushButton(Dialog)
        self.ninePushButton.setObjectName("ninePushButton")
        nineButtonFont = self.ninePushButton.font()
        nineButtonFont.setPointSize(16)
        self.ninePushButton.setFont(nineButtonFont)
        self.ninePushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.ninePushButton, 1, 3, 1, 1)
        self.subtractPushButton = QtWidgets.QPushButton(Dialog)
        self.subtractPushButton.setObjectName("subtractPushButton")
        subtractButtonFont = self.subtractPushButton.font()
        subtractButtonFont.setPointSize(16)
        self.subtractPushButton.setFont(subtractButtonFont)
        self.subtractPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.subtractPushButton, 2, 4, 1, 1)
        self.cubePushButton = QtWidgets.QPushButton(Dialog)
        self.cubePushButton.setObjectName("cubePushButton")
        cubeButtonFont = self.cubePushButton.font()
        cubeButtonFont.setPointSize(16)
        self.cubePushButton.setFont(cubeButtonFont)
        self.cubePushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.cubePushButton, 3, 0, 1, 1)
        self.onePushButton = QtWidgets.QPushButton(Dialog)
        self.onePushButton.setObjectName("onePushButton")
        oneButtonFont = self.onePushButton.font()
        oneButtonFont.setPointSize(16)
        self.onePushButton.setFont(oneButtonFont)
        self.onePushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.onePushButton, 3, 1, 1, 1)
        self.fivePushButton = QtWidgets.QPushButton(Dialog)
        self.fivePushButton.setObjectName("fivePushButton")
        fiveButtonFont = self.fivePushButton.font()
        fiveButtonFont.setPointSize(16)
        self.fivePushButton.setFont(fiveButtonFont)
        self.fivePushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.fivePushButton, 2, 2, 1, 1)
        self.threePushButton = QtWidgets.QPushButton(Dialog)
        self.threePushButton.setObjectName("threePushButton")
        threeButtonFont = self.threePushButton.font()
        threeButtonFont.setPointSize(16)
        self.threePushButton.setFont(threeButtonFont)
        self.threePushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.threePushButton, 3, 3, 1, 1)
        self.eightPushButton = QtWidgets.QPushButton(Dialog)
        self.eightPushButton.setObjectName("eightPushButton")
        eightButtonFont = self.eightPushButton.font()
        eightButtonFont.setPointSize(16)
        self.eightPushButton.setFont(eightButtonFont)
        self.eightPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.eightPushButton, 1, 2, 1, 1)
        self.undoPushButton = QtWidgets.QPushButton(Dialog)
        self.undoPushButton.setObjectName("undoPushButton")
        undoButtonFont = self.undoPushButton.font()
        undoButtonFont.setPointSize(16)
        self.undoPushButton.setFont(undoButtonFont)
        self.undoPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.undoPushButton, 0, 3, 1, 1)
        self.multiplyPushButton = QtWidgets.QPushButton(Dialog)
        self.multiplyPushButton.setObjectName("multiplyPushButton")
        multiplyButtonFont = self.multiplyPushButton.font()
        multiplyButtonFont.setPointSize(16)
        self.multiplyPushButton.setFont(multiplyButtonFont)
        self.multiplyPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.multiplyPushButton, 1, 4, 1, 1)
        self.dividePushButton = QtWidgets.QPushButton(Dialog)
        self.dividePushButton.setObjectName("dividePushButton")
        divideButtonFont = self.dividePushButton.font()
        divideButtonFont.setPointSize(16)
        self.dividePushButton.setFont(divideButtonFont)
        self.dividePushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.dividePushButton, 0, 4, 1, 1)
        self.twoPushButton = QtWidgets.QPushButton(Dialog)
        self.twoPushButton.setObjectName("twoPushButton")
        twoButtonFont = self.twoPushButton.font()
        twoButtonFont.setPointSize(16)
        self.twoPushButton.setFont(twoButtonFont)
        self.twoPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.twoPushButton, 3, 2, 1, 1)
        self.modulusPushButton = QtWidgets.QPushButton(Dialog)
        self.modulusPushButton.setObjectName("modulusPushButton")
        modulusButtonFont = self.modulusPushButton.font()
        modulusButtonFont.setPointSize(16)
        self.modulusPushButton.setFont(modulusButtonFont)
        self.modulusPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.modulusPushButton, 0, 0, 1, 1)
        self.squarePushButton = QtWidgets.QPushButton(Dialog)
        self.squarePushButton.setObjectName("squarePushButton")
        squareButtonFont = self.squarePushButton.font()
        squareButtonFont.setPointSize(16)
        self.squarePushButton.setFont(squareButtonFont)
        self.squarePushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.squarePushButton, 2, 0, 1, 1)
        self.clearPushButton = QtWidgets.QPushButton(Dialog)
        self.clearPushButton.setObjectName("clearPushButton")
        clearButtonsFont = self.clearPushButton.font()
        clearButtonsFont.setPointSize(16)
        self.clearPushButton.setFont(clearButtonsFont)
        self.clearPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.clearPushButton, 0, 1, 1, 2)
        self.sevenPushButton = QtWidgets.QPushButton(Dialog)
        self.sevenPushButton.setObjectName("sevenPushButton")
        sevenButtonsFont = self.sevenPushButton.font()
        sevenButtonsFont.setPointSize(16)
        self.sevenPushButton.setFont(sevenButtonsFont)
        self.sevenPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.sevenPushButton, 1, 1, 1, 1)
        self.fourPushButton = QtWidgets.QPushButton(Dialog)
        self.fourPushButton.setObjectName("fourPushButton")
        fourButtonsFont = self.fourPushButton.font()
        fourButtonsFont.setPointSize(16)
        self.fourPushButton.setFont(fourButtonsFont)
        self.fourPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.fourPushButton, 2, 1, 1, 1)
        self.sqrtPushButton = QtWidgets.QPushButton(Dialog)
        self.sqrtPushButton.setObjectName("sqrtPushButton")
        sqrtButtonsFont = self.sqrtPushButton.font()
        sqrtButtonsFont.setPointSize(16)
        self.sqrtPushButton.setFont(sqrtButtonsFont)
        self.sqrtPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.sqrtPushButton, 1, 0, 1, 1)
        self.zeroPushButton = QtWidgets.QPushButton(Dialog)
        self.zeroPushButton.setObjectName("zeroPushButton")
        zeroButtonsFont = self.zeroPushButton.font()
        zeroButtonsFont.setPointSize(16)
        self.zeroPushButton.setFont(zeroButtonsFont)
        self.zeroPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.zeroPushButton, 4, 2, 1, 1)
        self.negatePushButton = QtWidgets.QPushButton(Dialog)
        self.negatePushButton.setObjectName("negatePushButton")
        negateButtonsFont = self.clearPushButton.font()
        negateButtonsFont.setPointSize(16)
        self.negatePushButton.setFont(negateButtonsFont)
        self.negatePushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.negatePushButton, 4, 1, 1, 1)
        self.decimalPushButton = QtWidgets.QPushButton(Dialog)
        self.decimalPushButton.setObjectName("decimalPushButton")
        decimalButtonsFont = self.clearPushButton.font()
        decimalButtonsFont.setPointSize(16)
        self.decimalPushButton.setFont(decimalButtonsFont)
        self.decimalPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.decimalPushButton, 4, 3, 1, 1)
        self.enterPushButton = QtWidgets.QPushButton(Dialog)
        self.enterPushButton.setObjectName("enterPushButton")
        enterButtonsFont = self.enterPushButton.font()
        enterButtonsFont.setPointSize(16)
        self.enterPushButton.setFont(enterButtonsFont)
        self.enterPushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.enterPushButton, 4, 4, 1, 1)
        self.inversePushButton = QtWidgets.QPushButton(Dialog)
        self.inversePushButton.setObjectName("inversePushButton")
        inverseButtonsFont = self.clearPushButton.font()
        inverseButtonsFont.setPointSize(16)
        self.inversePushButton.setFont(inverseButtonsFont)
        self.inversePushButton.setMinimumSize(110, 90)
        self.buttonsGridLayout.addWidget(self.inversePushButton, 4, 0, 1, 1)
        self.calculationsVerticalLayout.addLayout(self.buttonsGridLayout)
        self.overallHorizontalLayout.addLayout(self.calculationsVerticalLayout)
        self.historyVerticalLayout = QtWidgets.QVBoxLayout()
        self.historyVerticalLayout.setContentsMargins(5, 5, 5, 5)
        self.historyVerticalLayout.setObjectName("historyVerticalLayout")
        self.historyLabel = QtWidgets.QLabel(Dialog)
        self.historyLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.historyLabel.setObjectName("historyLabel")
        historyLabelFont = self.historyLabel.font()
        historyLabelFont.setPointSize(11)
        self.historyLabel.setFont(historyLabelFont)
        self.historyVerticalLayout.addWidget(self.historyLabel)
        self.historyListWidget = QtWidgets.QListWidget(Dialog)
        self.historyListWidget.setObjectName("historyListWidget")
        self.historyListWidget.setMinimumSize(300, 100)
        self.historyVerticalLayout.addWidget(self.historyListWidget)
        self.overallHorizontalLayout.addLayout(self.historyVerticalLayout)
        self.gridLayout.addLayout(self.overallHorizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculator"))
        self.addPushButton.setText(_translate("Dialog", "+"))
        self.sixPushButton.setText(_translate("Dialog", "6"))
        self.ninePushButton.setText(_translate("Dialog", "9"))
        self.subtractPushButton.setText(_translate("Dialog", "-"))
        self.cubePushButton.setText(_translate("Dialog", "x" + u'\xb3'))
        self.onePushButton.setText(_translate("Dialog", "1"))
        self.fivePushButton.setText(_translate("Dialog", "5"))
        self.threePushButton.setText(_translate("Dialog", "3"))
        self.eightPushButton.setText(_translate("Dialog", "8"))
        self.undoPushButton.setText(_translate("Dialog", "UNDO"))
        self.multiplyPushButton.setText(_translate("Dialog", "X"))
        self.dividePushButton.setText(_translate("Dialog", "/"))
        self.twoPushButton.setText(_translate("Dialog", "2"))
        self.modulusPushButton.setText(_translate("Dialog", "%"))
        self.squarePushButton.setText(_translate("Dialog", "x" + u'\xb2'))
        self.clearPushButton.setText(_translate("Dialog", "CLEAR"))
        self.sevenPushButton.setText(_translate("Dialog", "7"))
        self.fourPushButton.setText(_translate("Dialog", "4"))
        self.sqrtPushButton.setText(_translate("Dialog", u'\u221a'))
        self.zeroPushButton.setText(_translate("Dialog", "0"))
        self.negatePushButton.setText(_translate("Dialog", "(-)"))
        self.decimalPushButton.setText(_translate("Dialog", "."))
        self.enterPushButton.setText(_translate("Dialog", "ENTER"))
        self.inversePushButton.setText(_translate("Dialog", "1/x"))
        self.historyLabel.setText(_translate("Dialog", "History:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
